### ISSUE TITLE
server not run

### ISSUE THREAD

**Issue by ixayldz** [glenndehaan/csgo-matchmaking#4]
[root@localhost server]# npm start

> csgo-matchmaking-server@0.0.0 start /var/www/html/server
> node server.js

/var/www/html/server/node_modules/ws/lib/websocket.js:354
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/server/node_modules/ws/index.js:3:19)

npm ERR! Linux 3.10.0-1160.31.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! csgo-matchmaking-server@0.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the csgo-matchmaking-server@0.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the csgo-matchmaking-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs csgo-matchmaking-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls csgo-matchmaking-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/server/npm-debug.log
[root@localhost server]#

**Comment by glenndehaan** [comment]
You are running node 6 but node 8 is required for this project. As explained in the Readme.

**Comment by ixayldz** [comment]
myfriend can i ask you this
this script is working now ?
there is website template or no ?
is it similar like faceit or popflash?
how i will understand is it working or not :D

Glenn de Haan ***@***.***>, 21 Haz 2021 Pzt, 11:48 tarihinde
şunu yazdı:

**Comment by glenndehaan** [comment]
Yes the project is working fine. But is a bit old.
Also it's more like a prototype then a full featured application.
There is no website it's just a terminal application.

And no it doesn't even come close to a faceit or popflash service. But that was never the idea.

It's a terminal application that connects to a server via websockets. So no HTTP here.... the server has a pool of csgo server ip's and ports. When enough players are ready. So for competitive that will be 10. A free server IP is given to the group. Then a timer starts that roughly takes 110 minutes. Since a match can't be longer then that and then puts the server back in the ready pool.

**Comment by ixayldz** [comment]
thank you man u explaining very well and very fast.  Myfriend lots people
looking like this script for own matchmaking system for own country csgo
servers. why u dont keep do this full finish and update like faceit ? no
need tournament mode just need 5vs5 match script teams balance with elo
can u complete this with web site also ?

Glenn de Haan ***@***.***>, 21 Haz 2021 Pzt, 12:07 tarihinde
şunu yazdı:

**Comment by glenndehaan** [comment]
I had 2 reasons why I stopped this project and uploaded the files to GitHub just for others to maybe continue what I started:

1. I stopped playing CSGO after the CS matchmaking got destroyed by cheaters and farm bots.
2. My intention was always to use the Steam API to verify a users account. That way the system is less prone to cheating (since we can monitor and track a users account) and thus is able to implement/track ELO correctly. Also this meant I didn't have to build a user management/account system since I could use the Steam API. But just as I started the project the Steam API got shutdown and later a much stripped down version was but back (this was during the whole CSGO skin gambling time).
 

This was one of the primary reasons that I stopped the project. I did setup one other project: https://github.com/glenndehaan/csgo-rcon-nodejs

This project focuses more on the LAN Party type of CSGO tournaments. Where an admin can control the entire server base and monitor/manage match info (partially automated since this is a webportal that communicates to and from the csgo server, something this application doesn't do). But this project didn't manage to get a lot of attention by others in the community so I also spend less and less time on it at the end.

**Comment by ixayldz** [comment]
Myfriend in turkey we have 1 million csgo player and they hate faceit esea
because no turkish csgo server. İf i open smilar matchmaking system it will
be very populer. By the way there is easyanticheat project its cool for
csgo server i will add that anticheat to my servers man pls finish match
find queue system for website plsss

21 Haz 2021 Pzt, saat 12:25 tarihinde Glenn de Haan <
***@***.***> şunu yazdı:
